### PR TITLE
fix(hive): disable ssl for metastore

### LINKED ISSUE #402: spark-sql: Cannot connect to Hive Metastore
While `pyspark(3)` and `spark(3)-shell` can successfully interact with the Hive Metastore after #401, the `spark(3)-sql` CLI cannot connect to the Hive Metastore. We have the following error:
```
2022-08-03 09:37:51,153 WARN hive.metastore: Failed to connect to the MetaStore Server...
...
Caused by: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
	at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1523)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:86)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:132)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)
	at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3005)
	at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3024)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)
	... 12 more
...
Caused by: MetaException(message:Could not connect to meta store using any of the URIs provided. Most recent failure: org.apache.thrift.transport.TTransportException: Invalid status 21
```

The error occurs at different steps between Spark 2 and Spark 3:
- For `spark-sql`, it fails at instantiation
- For `spark3-sql`, it fails when trying to read a table:
  ```
  Hive Session ID = 6de6d09a-2733-4f52-a5bb-8bae91afc52b
  Spark master: yarn, Application Id: application_1659513794139_0021
  spark-sql> show tables in tdp_user_db;
  table1
  Time taken: 1.715 seconds, Fetched 1 row(s)
  spark-sql> select * from tdp_user_db.table1;
  2022-08-03 09:42:13,301 WARN session.SessionState: METASTORE_FILTER_HOOK will be ignored, since hive.security.authorization.manager is set to instance of HiveAuthorizerFactory.
  2022-08-03 09:42:13,374 WARN hive.metastore: Failed to connect to the MetaStore Server...
  2022-08-03 09:42:18,381 WARN hive.metastore: Failed to connect to the MetaStore Server...
  2022-08-03 09:42:23,388 WARN hive.metastore: Failed to connect to the MetaStore Server...
  2022-08-03 09:42:28,434 ERROR session.SessionState: Error setting up authorization: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
  ```

There are probably some missing properties in the Spark `hive-site.xml`. We can see those warnings when running `spark-sql`:
```
2022-08-03 09:37:50,942 WARN conf.HiveConf: HiveConf of name hive.metastore.uri.selection does not exist
2022-08-03 09:37:50,949 WARN conf.HiveConf: HiveConf of name hive.metastore.truststore.path does not exist
2022-08-03 09:37:50,950 WARN conf.HiveConf: HiveConf of name hive.metastore.truststore.password does not exist
2022-08-03 09:37:50,950 WARN conf.HiveConf: HiveConf of name hive.metastore.use.SSL does not exist
```

### PR DESCRIPTION
**Pull request by Nuttymoon**
#### Which issue(s) this PR fixes:

Fixes #402

#### Additional comments:

As stated by @gboutry, disabling SSL on Hive Metastore side solves the issues. Connections to the Metastore are still secured via SASL/Kerberos. There is no more need to remove `spark-sql` and `spark3-sql` as are functional after this fix.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by gboutry** [comment]
Therefore, we should remove the ssl-tls tasks for hive metastore

**Comment by leopaul36** [comment]
Shouldn't we try to backport [HIVE-15025](https://issues.apache.org/jira/browse/HIVE-15025) before disabling SSL for Hive MS?

**Comment by gboutry** [comment]
> Shouldn't we try to backport [HIVE-15025](https://issues.apache.org/jira/browse/HIVE-15025) before disabling SSL for Hive MS?

Where do you want to backport this ?
The hive metastore we deploy is deployed in 3.1.X.
The hive version that's used to compile with spark is in 2.3.X which should already have the patch.

**Comment by Nuttymoon** [comment]
> Shouldn't we try to backport [HIVE-15025](https://issues.apache.org/jira/browse/HIVE-15025) before disabling SSL for Hive MS?

If I understand correctly the purpose of this patch is only to allow the use SSL **when Kerberos is not used**:
> SSL encryption is only used to encrypt the communication to HMS when no kerberos authentication is enabled for HMS.
This is not the case of TDP.

**Comment by leopaul36** [comment]
> > Shouldn't we try to backport [HIVE-15025](https://issues.apache.org/jira/browse/HIVE-15025) before disabling SSL for Hive MS?
> 
> Where do you want to backport this ? The hive metastore we deploy is deployed in 3.1.X. The hive version that's used to compile with spark is in 2.3.X which has the patch.

Yes my bad, I had in the mind our Hive 1.x and 2.x that we build for Spark but this issue is not related

**Comment by gboutry** [comment]
It's outside the scope of this PR, but we should check the properties listed in the hive-sites, because some have been deprecated for a long time. For example, all properties starting with `hive.metastore...` for metastore configuration have been deprecated to `metastore...` since the metastore became a standalone project (in hive repository, project: `standalone-metastore`).

**Review by gboutry — APPROVED** [review]

**Review by leopaul36 — APPROVED** [review]

**Pull request merged**
