### PR TITLE
feat(hue): enable application log on jobbrowser of hue

### PR DESCRIPTION
**Pull request by nschung**
#### Which issue(s) this PR fixes

Give hue user  access to yarn and spark application log

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Review by mehdibn — APPROVED** [review]

**Review by rpignolet — APPROVED** [review]

**Comment by gonzaloetjo** [comment]
I'm considering the implications of adding additional components to `tdp-collections`. Would it be more appropriate to introduce this as an override within `tdp-getting-started`? Instead of adding extras dependencies on collections. 

Additionally, I was evaluating the possibility of having a dedicated overrides directory for `tdp-collections-extras` (or similar community collections). This would allow extras to inject variables into collections more seamlessly. The `tdp init` process could then prioritize these overrides before deployment. What are your thoughts on this approach?

**Comment by rpignolet** [comment]
We cannot add a value to a string with the current override mechanism. This chain would have to be a dict if we wanted to do it.

**Comment by gonzaloetjo** [comment]
I was leaning more towards the idea of overriding the entire key using an `tdp-collection-extras` overrides folder, which would contain the additions and the original values, similar to those in this commit. A dict might be a solution to.

**Comment by rpignolet** [comment]
I think we should not duplicate a variable from `tdp-collection` in `tdp-collection-extra`. In the case of modifying the variable in `tdp-collection`, if we forget to make the modification in `tdp-collection-extra` this will cause us problems. We must stick to the behavior that `tdp-collection-extra` adds variables or adds elements into an existing variable but not a complete override.

If Hue is not deployed in the cluster, I think it is not a concern for it to be present in the configuration in `tdp-collection` unless it prevents Hadoop from working.

The alternative would be to change these variables to dict but I don't think we gain anything there.

**Comment by gonzaloetjo** [comment]
>The alternative would be to change these variables to dict but I don't think we gain anything there.

IMO we gain for the-collection-extras, or any other community collection, to be independent from tdp-collections, as more and more external variables might be declared in tdp-collection. But that's about it.

**Comment by rpignolet** [comment]
I agree to make dicts but how can we know that certain variable must be a dict? Do we look for all the variables to put them in dict or do we change them to dict only if necessary?

**Comment by rpignolet** [comment]
As discuss, will be done in #801.

**Pull request merged**
