### PR TITLE
fix(spark3): make hbase dependency deployment optional

### LINKED ISSUE #362: spark3: make hbase dependency deployment optional

### PR DESCRIPTION
**Pull request by mehdibn**
#### Which issue(s) this PR fixes:

Fixes #362 

#### Additional comments:

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Review by nolimitkun — APPROVED** [review]

**Comment by mehdibn** [comment]
We can add a boolean var in order to enable it or not, what do you think @rpignolet @leopaul36 ?

**Comment by mehdibn** [comment]
or i can add another condition : `if spark_hbase_dist_file != ""`

**Comment by leopaul36** [comment]
> or i can add another condition : `if spark_hbase_dist_file != ""`

Yes i think this would be good

**Comment by rpignolet** [comment]
What the difference between `if spark_hbase_dist_file is defined` and `if spark_hbase_dist_file != ""` ? This feature can not be disabled with Ansible inventory so I think an explicit variable `spark_hbase_connector_enable: yes` is better. Tell the user to put empty string for `spark_hbase_dist_file` to disable the feature is weird.

**Comment by leopaul36** [comment]
> What the difference between `if spark_hbase_dist_file is defined` and `if spark_hbase_dist_file != ""` ? This feature can not be disabled with Ansible inventory so I think an explicit variable `spark_hbase_connector_enable: yes` is better. Tell the user to put empty string for `spark_hbase_dist_file` to disable the feature is weird.

Agreed, the empty string is weird on second thought

**Pull request merged**
