### PR TITLE
387 hadoop credential for password

### LINKED ISSUE #387: Use CredentialProvider to store passwords or restrict file access when not possible
A significant number of passwords are stored in plain text in configuration files that are accessible by any user:
- `/etc/hadoop/conf.*/ssl-client.xml`: `ssl.client.truststore.password`
- `/etc/(hadoop|hbase)/conf.*/ssl-server.xml`: `ssl.server.keystore.password`, `ssl.server.truststore.password`
- `/etc/hadoop/conf.*/hive-site.xml`: `hive.metastore.keystore.password`, `hive.metastore.truststore.password`, `hive.server2.keystore.password`
-  `/etc/spark/conf.hs/spark-default.conf`: `spark.ssl.historyServer.keyStorePassword`
- `/etc/hbase/conf.*/hbase-site.xml`: `hbase.rest.ssl.keystore.password`, `phoenix.queryserver.tls.keystore.password`
- `/opt/tdp/ranger-*-plugin/install.properties`: `SSL_KEYSTORE_PASSWORD`, `SSL_TRUSTSTORE_PASSWORD`

We should use [Hadoop CredentialProvider](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/CredentialProviderAPI.html) to store passwords to avoid having them in plaintext. The `hive` role already makes use of this feature to store the Metastore DB password.

We should create a role in `utils` for this purpose to make it generic.

For Ranger plugins, `install.properties` files should not be readable by random users.

**Note:** I did not find any other passwords but there might be.

### PR DESCRIPTION
**Pull request by leopaul36**
#### Which issue(s) this PR fixes

Fixes #387 

#### Additional comments

Some remarks:

- `hadoop.security.credential.provider.path` is a `core-site.xml` property but I chose not to put it in the `core_site` dict since it is only copied from hadoop/client and not rendered for all services. I also think it makes more sense to put the store path in the site of the properties it holds (`ssl-server.xml` most of the time, `hbase-site.xml` for HBase REST).
- I also chose this to have a different credential store per component so we can still have different truststore / keystore files if needed.
- Hadoop HttpFs was using SSL through env vars. I switched to properties stored in `ssl-server.xml`.
- I removed the `ssl-server.xml` of HBase REST since it was useless.
- I did not implement the Hadoop credentials file in Spark 2 since our version is lacking the support for this [SPARK-24518](https://issues.apache.org/jira/browse/SPARK-24518).

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Review by rpignolet — APPROVED** [review]

**Comment by mehdibn** [comment]
nice PR @leopaul36 :1st_place_medal:

**Review by mehdibn — APPROVED** [review]

**Comment by rpignolet** [comment]
For my test I rebased this branch on master and it is not working for me when running `hdfs_ssl-tls_install.yml`:
```
TASK [tosit.tdp.jceks : Create JCEKS file /etc/hadoop/conf.nn/hadoop.jceks] ****************************************
failed: [rpignolet-master-01] (item=None) => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
    "changed": true
}
```
I remove the `no_log` flag to show the error:
```
failed: [rpignolet-master-01] (item={'property': 'ssl.server.truststore.password', 'value': 'Truststore123!'}) => {
    "ansible_loop_var": "item",
    "changed": true,
    "cmd": [
        "/opt/tdp/hadoop/bin/hadoop",
        "credential",
        "create",
        "ssl.server.truststore.password",
        "-value",
        "Truststore123!",
        "-provider",
        "localjceks://file/etc/hadoop/conf.nn/hadoop.jceks"
    ],
    "delta": "0:00:00.045827",
    "end": "2023-02-04 14:01:52.838484",
    "item": {
        "property": "ssl.server.truststore.password",
        "value": "Truststore123!"
    },
    "rc": 1,
    "start": "2023-02-04 14:01:52.792657"
}

STDERR:

WARNING: log4j.properties is not found. HADOOP_CONF_DIR may be incomplete.
ERROR: JAVA_HOME is not set and could not be found.


MSG:

non-zero return code
```
Same when running the command via ssh:
```
[root@rpignolet-master-01 ~]# /opt/tdp/hadoop/bin/hadoop credential create ssl.server.truststore.password -value Truststore123! -provider localjceks://file/etc/hadoop/conf.nn/hadoop.jceks
WARNING: log4j.properties is not found. HADOOP_CONF_DIR may be incomplete.
ERROR: JAVA_HOME is not set and could not be found.
```
A problem with `JAVA_HOME` env var ?

**Comment by leopaul36** [comment]
It worked with a fresh `tdp_getting-started` on my side. My guess is that your `hdfs_nn` is not a `hdfs_client` so you don't have `/etc/hadoop/conf` on the node at this point. I rebased on master and added the feature to configure the Hadoop config dir for the JCEKS action and implemented it in HDFS services. We should not need it in the other components since they depend on `hadoop_client`.

Can you retest with this @rpignolet?

**Comment by rpignolet** [comment]
@leopaul36 Same error with a fresh deployment.
```
failed: [rpignolet-master-01] (item={'property': 'ssl.client.truststore.password', 'value': 'Truststore123!'}) => {
    "ansible_loop_var": "item",
    "changed": true,
    "cmd": [
        "/opt/tdp/hadoop/bin/hadoop",
        "--config",
        "/etc/hadoop/conf.nn",
        "credential",
        "create",
        "ssl.client.truststore.password",
        "-value",
        "Truststore123!",
        "-provider",
        "localjceks://file/etc/hadoop/conf.nn/hadoop.jceks"
    ],
    "delta": "0:00:00.046718",
    "end": "2023-02-06 14:15:45.802918",
    "item": {
        "property": "ssl.client.truststore.password",
        "value": "Truststore123!"
    },
    "rc": 1,
    "start": "2023-02-06 14:15:45.756200"
}

STDERR:

WARNING: log4j.properties is not found. HADOOP_CONF_DIR may be incomplete.
ERROR: JAVA_HOME is not set and could not be found.


MSG:

non-zero return code
```

**Comment by leopaul36** [comment]
I realize my last changes where useless because the issue is that `hdfs_namenode_config` depends on `hdfs_ssl-tls_install` so the hadoop-env.sh with `JAVA_HOME` is not yet there anyway while running `hdfs_ssl-tls_install`.

I will revert the last commit.

I think it works on my side because `JAVA_HOME`  is configured in `/etc/environment` with `roles/system/tasks/java_home.yml` at `tdp-collection-prerequisites`.

**Comment by leopaul36** [comment]
I added `JAVA_HOME` to the credentials command, should be fine now.

**Comment by rpignolet** [comment]
In our deployment we do not add the `JAVA_HOME` into `/etc/environment` that why we have the problem but it is not a prerequisite because it works without it currently.

**Review by rpignolet — APPROVED** [review]
It works !

**Review by nschung — APPROVED** [review]

**Comment by leopaul36** [comment]
> In our deployment we do not add the `JAVA_HOME` into `/etc/environment` that why we have the problem but it is not a prerequisite because it works without it currently.

Yes I'm not sure why we did it but it could be removed in `tdp-collection-prerequisites`.

**Pull request merged**
