### PR TITLE
zookeeper: service check

### PR DESCRIPTION
**Pull request by kpgtek**
Fix [#114](https://github.com/TOSIT-IO/tdp-collection/issues/114), add Sanity checks to Zookeeper service:

- check Zookeeper commands by "The Four Letter Words"
- check "create / remove" znode, with `zkCli.sh`

### CODE REVIEW

**Comment by kpgtek** [comment]
Before starting the check, we could verify the service port availability and after the timeout, the check is failed (Ansible ```wait_for``` module), what do you think?

**Comment by rpignolet** [comment]
Tasks to remove:
- `Check CMD "conf"`
- `Check CMD "envi"`
- `Check CMD "srvr" for mode`
- `Check CMD "crst" (reset connection stats)`
- `Check CMD "srst" (reset server stats)`
- `Check CMD "cons"`
- `Check CMD "stat" for mode`
- `Check CMD "dump"`
- `Check CMD "wchs"`

`znode` creation stay in service check but all other (`ruok`, etc.) move to component check.

**Comment by kpgtek** [comment]
This PR needs the issue #253 to be fixed (it needs ```zookeeper``` ports variables).

**Review by rpignolet — APPROVED** [review]

**Review by leopaul36 — APPROVED** [review]

**Comment by leopaul36** [comment]
I squashed this one as there were a lot of commits

**Pull request merged**
