### PR TITLE
feat: add status tasks and playbooks

### LINKED ISSUE #186: all: get systemd service(tdp component) status
as a user of TDP, I would like to get all component status after cluster has been deployed.
proposition : use ansible service_facts

### LINKED ISSUE #631: Implement status check playbooks
We already have playbooks to stop, start or restart services. We should implement `status` playbooks that run `systemctl status $service`.

This is a prerequisite to automating a regular check of the systemd services and exposing the results through tdp-lib / tdp-server.

### PR DESCRIPTION
**Pull request by leopaul36**
#### Which issue(s) this PR fixes

Fixes #631 
Fixes #186 

#### Additional comments

I did not add the status tasks in the DAG yet because I'm not sure where to put them. A `*_*_status` should depend on `*_*_start` but do we want `*_*_init` tasks to depend on `*_*_status` tasks? 

I don't have a strong opinion but I guess it would improve overall trust in a deployment since some services can fail silently a few seconds after the `*_*_start` task. But those might be missed anyway in the case where a service is in a restart loop.

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by rpignolet** [comment]
IMO `*_status` is not in the DAG, but `*_check` will be in the DAG to check if the startup was successful.

**Review by rpignolet — APPROVED** [review]

**Review by gboutry — APPROVED** [review]

**Comment by leopaul36** [comment]
> IMO `*_status` is not in the DAG, but `*_check` will be in the DAG to check if the startup was successful.

About this if we stick with our current design that `*_init` are the last tasks of the DAG and make:
- `*_check` tasks depend on `*_start`
- `*_init` tasks depend on `*_check` (rather than `*_start` like we have now)

Do you agree with this @rpignolet @gboutry before I do a PR?

**Comment by rpignolet** [comment]
No `*_check` depends on `*_init`. For some service/component, without `*_init` the service/component does not work so the `*_check` will fail if it runs before `*_init` no ?

**Comment by leopaul36** [comment]
> No `*_check` depends on `*_init`. For some service/component, without `*_init` the service/component does not work so the `*_check` will fail if it runs before `*_init` no ?

In our current logic, "init" means a component is installed / configured / started / **ready to use**. With the check we add more trust to the "ready to use" status so I think it's logic than `*_init` depends on `*_check`.

I think my problem here is the fact that some `*_init` are not `noop: yes`. Maybe we should introduce `*_ready` nodes in the DAG.

For example in Ambari, the logic stops at "ready to use". If for some reason HDFS is not working after it's been (re)deployed, the deploy action is still considered successful.

**Pull request merged**
