### PR TITLE
refactor: migrate to ansible-core-2.15

### LINKED ISSUE #774: Update Ansible version from ansible-2.9 to ansible-core-2.15
After #773, we should update the `ansible-core` version from 2.9 to 2.15 to match the highest version available with Python 3.9.

See https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix

### PR DESCRIPTION
**Pull request by rpignolet**
- use ansible module full name
- remove "warn" for "command" module which is not needed now
- refactor "label" inside "loop_control" to use string type
- use shebang "#!/usr/bin/python" for module as written in the doc
- remove plugin shebang when it does not contains a "main" function
- update ansible-lint version and configuration

#### Which issue(s) this PR fixes

Fixes #774 

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by PaulFarault** [comment]
Well nice work!

You may also want to rewrite the installation section of the README which still mentions Ansible 2.9 and 2.10.

**Comment by rpignolet** [comment]
Yes README should be updated but for now I only did the ansible code migration.

Following ansible-lint update, I do not resolve all warning because I don't know how to solve them for now. Eventually all warning should be fixed with new PR.

**Comment by kpgtek** [comment]
In [utils/ranger_policies](https://github.com/TOSIT-IO/tdp-collection/blob/master/roles/utils/ranger_policies/tasks/main.yml),
```
  loop_control:
    label:
```
is not using a string, and this is not working with Ansible Core 2.15.

**Comment by rpignolet** [comment]
> In [utils/ranger_policies](https://github.com/TOSIT-IO/tdp-collection/blob/master/roles/utils/ranger_policies/tasks/main.yml),
> 
> ```
>   loop_control:
>     label:
> ```
> 
> is not using a string, and this is not working with Ansible Core 2.15.

Good catch, should be solved.

**Review by kpgtek — APPROVED** [review]

**Comment by rpignolet** [comment]
Force push to resolve conflicts.

**Pull request merged**
